var gVNResource = {
    AccountInfo: 'Thông tin tài khoản',
    Account: 'Tài khoản',
    Activity: 'Hoạt động',
    Announcement: 'Thông báo',
    Back: 'Trở về',
    Cancel: 'Hủy',
    Cashier: 'Thu ngân',
    ChangePassword: 'Đổi mật khẩu',
    ChartRevenueWeek: 'Biểu đồ doanh số tuần',
    Customers: 'Khách hàng',
    Day: 'Day',
    Debit: 'Nợ',
    DebtOrders: 'Đơn hàng còn nợ',
    English: 'Tiếng Anh',
    Email: 'Email',
    EmployeeCode: 'Mã nhân viên',
    EmployeeName: 'Tên nhân viên',
    Exception: 'Exception',
    Exit: 'Thoát',
    ExportExcel: 'Xuất Excel',
    General: 'Tổng Quan',
    FromDate: 'Từ ngày',
    LastMonth: 'Tháng trước',
    LastQuarter: 'Quí trước',
    LastWeek: 'Tuần trước',
    ListProducts: 'Danh sách hàng hóa',
    LogData: 'Data Log',
    Login: 'Đăng nhập',
    LongWaiting: 'Tồn kho lâu',
    Info: 'Thông tin',
    Inventory: 'Tồn kho',
    InventoryInfo: 'Thông tin kho',
    NewPassword: 'Mật khẩu mới',
    NoAnnouncement: 'Chưa có thông báo!',
    NoDataFound: 'Không có dữ liệu!',
    NotYetPrice: 'Chưa làm giá bán',
    NotYetCost: 'Chưa nhập giá mua',
    NotYetGroup: 'Hàng chưa phân loại',
    NumOrder: 'Số đơn hàng',
    NumProduct: 'Số hàng hóa',
    NumRow: 'Số dòng',
    MakeOrder: 'Bán hàng',
    MakeOrder2: 'Tạo đơn hàng',
    MessageEnterAccount: 'Vui lòng nhập tài khoản đăng nhập.',
    MessageEnterPassword: 'Vui lòng nhập mật khẩu.',
    MessageNewPassword: 'Vui lòng nhập mật khẩu mới.',
    MessageNoAccess: 'Bạn không có quyền truy cập vào trang này. Vui lòng liên hệ admin',
    MessageOldPassword: 'Vui lòng nhập mật khẩu hiện tại.',
    MessageSelectProduct: 'Vui lòng chọn hàng hóa cho đơn hàng.',
    MessageRepeatPassword: 'Vui lòng nhập lại mật khẩu mới.',
    Month: 'Tháng',
    OldPassword: 'Mật khẩu cũ',
    OutOfStore: 'Hết hàng',
    Orders: 'Đơn hàng',
    Order: 'Đơn hàng',
    OrderCode: 'Mã đơn hàng',
    OverLimit: 'Vượt định mức',
    Quantity: 'Số lượng',
    Quarter: 'Quí',
    Password: 'Mật khẩu',
    Payment: 'Thu chi',
    PlaceholderOrder: 'Nhập mã đơn hàng hoặc thông tin khách hàng (mã, tên, SĐT)',
    PlaceholderOrderDetail: 'Nhập mã hoặc tên hàng hóa',
    PhoneNumber: 'Số điện thoại',
    POS: 'POS - Bán hàng',
    POSDesc: 'Nhấp vào đây để bán hàng',
    Price: 'Giá bán',
    PrintOrder: 'In đơn hàng',
    Products: 'Hàng hóa',
    ProductInfo: 'Thông tin hàng hóa',
    ProductCode: 'Mã hàng',
    ProductName: 'Tên hàng hóa',
    Profit: 'Lợi nhuận',
    Purchase: 'Nhập kho',
    TempSave: 'Lưu tạm',
    ToDate: 'Đến ngày',
    TodayActivity: 'Hoạt động hôm nay',
    Total: 'Tổng',
    ThisMonth: 'Tháng này',
    ThisWeek: 'Tuần này',
    Save: 'Lưu',
    SaveAndPrint: 'Lưu và in',
    Setting: 'Thiết lập',
    SoldDate: 'Ngày bán',
    SQL: 'SQL',
    Status: 'Trạng thái',
    Store: 'Cửa hàng',
    StoreManagement: 'Quản lý cửa hàng',
    STT: 'STT',
    SumMoney: 'Tổng tiền',
    SumOrder: 'Tổng hóa đơn',
    SumPrice: 'Thành tiền',
    Remain: 'Còn tồn',
    RememberPassword: 'Ghi nhớ tài khoản',
    RemovedOrder: 'Đơn hàng bị xóa',
    RepeatPassword: 'Nhập lại mật khẩu',
    Revenue: 'Doanh số',
    UnderLimit: 'Dưới định mức',
    UserRole: 'Nhóm người dùng',
    Vietnamese: 'Tiếng Việt',
    Week: 'Tuần'
}
//<span ng-bind="Language.Resource.StoreManagement"></span>
var gENResource = {
    AccountInfo: 'Account Info',
    Account: 'Account',
    Activity: 'Activity',
    Announcement: 'Announcement',
    Back: 'Back',
    Cancel: 'Cancel',
    Cashier: 'Cashier',
    ChangePassword: 'Change Password',
    ChartRevenueWeek: 'Chart revenue in week',
    Customers: 'Customers',
    Day: 'Day',
    Debit: 'Debit',
    DebtOrders: 'Orders With Debit',
    English: 'English',
    Email: 'Email',
    EmployeeCode: 'Employee Code',
    EmployeeName: 'Employee Name',
    Exception: 'Exception',
    Exit: 'Exit',
    ExportExcel: 'Export Excel',
    General: 'General',
    FromDate: 'From Date',
    LastMonth: 'Last month',
    LastQuarter: 'Last Quarter',
    LastWeek: 'Last week',
    ListProducts: 'List Products',
    LogData: 'Data Log',
    Login: 'Log in',
    LongWaiting: 'Long waiting',
    Info: 'Information',
    Inventory: 'Inventory',
    InventoryInfo: 'Inventory Info',
    NewPassword: 'New Password',
    NoAnnouncement: 'No announcement!',
    NoDataFound: 'No Data Found!',
    NotYetPrice: 'Not input price',
    NotYetCost: 'Not input cost',
    NotYetGroup: 'Not input group',
    NumOrder: 'Num of Orders',
    NumProduct: 'Num of Products',
    NumRow: 'Num rows',
    MakeOrder: 'Make Order',
    MakeOrder2: 'Make Order',
    MessageEnterAccount: 'Please enter your account.',
    MessageEnterPassword: 'Please enter your password.',
    MessageNewPassword: 'Please enter new password.',
    MessageNoAccess: 'You don\'t have permission to access this page. Please contact to admin.',
    MessageOldPassword: 'Please enter old password.',
    MessageSelectProduct: 'Please select at least one product.',
    MessageRepeatPassword: 'Please repeat password.',
    Month: 'Month',
    OldPassword: 'Old password',
    OutOfStore: 'Out of Store',
    Orders: 'Orders',
    Order: 'Order',
    OrderCode: 'Order Code',
    OverLimit: 'Over limit',
    Quantity: 'Quantity',
    Quarter: 'Quarter',
    Password: 'Password',
    Payment: 'Payment',
    PlaceholderOrder: 'Enter order code or customer\'s information (code, name, phone)',
    PlaceholderOrderDetail: 'Enter product code or name',
    PhoneNumber: 'Phone Number',
    POS: 'POS - Selling',
    POSDesc: 'Click here to make orders',
    Price: 'Price',
    PrintOrder: 'Print Order',
    Products: 'Products',
    ProductInfo: 'Product Info',
    ProductCode: 'Product Code',
    ProductName: 'Product Name',
    Profit: 'Profit',
    Purchase: 'Purchase',
    TempSave: 'Temp Save',
    ToDate: 'To Date',
    TodayActivity: 'Today Activity',
    Total: 'Total',
    ThisMonth: 'This month',
    ThisWeek: 'This week',
    Save: 'Save',
    SaveAndPrint: 'Save and Print',
    Setting: 'Setting',
    SoldDate: 'Sold Date',
    SQL: 'SQL',
    Status: 'Status',
    Store: 'Store',
    StoreManagement: 'Store Management',
    STT: 'No',
    SumMoney: 'Sum Money',
    SumOrder: 'Num of Orders',
    SumPrice: 'Sum Price',
    Remain: 'Remain',
    RememberPassword: 'Remember Password',
    RepeatPassword: 'Repeat Password',
    RemovedOrder: 'Removed Orders',
    Revenue: 'Revenue',
    UnderLimit: 'Under limit',
    UserRole: 'User Role',
    Vietnamese: 'Vietnamese',
    Week: 'Week'
}