var gVNResource = {
    General: 'Tổng Quan',
    Orders: 'Đơn hàng',
    Products: 'Hàng hóa',
    Customers: 'Khách hàng',
    Purchase: 'Nhập kho',
    Inventory: 'Tồn kho',
    Revenue: 'Doanh số',
    Payment: 'Thu chi',
    Profit: 'Lợi nhuận',
    Setting: 'Thiết lập',
    Exception: 'Exception',
    LogData: 'Data Log',
    Announcement: 'Thông báo',
    SQL: 'SQL',
    StoreManagement: 'Quản lý cửa hàng',
    POS: 'POS - Bán hàng',
    Info: 'Thông tin',
    Exit: 'Thoát',
    POSDesc: 'Nhấp vào đây để bán hàng',
    Vietnamese: 'Tiếng Việt',
    English: 'Tiếng Anh'
}
//<span ng-bind="Language.Resource.StoreManagement"></span>
var gENResource = {
    General: 'General',
    Orders: 'Orders',
    Products: 'Products',
    Customers: 'Customers',
    Purchase: 'Purchase',
    Inventory: 'Inventory',
    Revenue: 'Revenue',
    Payment: 'Payment',
    Profit: 'Profit',
    Setting: 'Setting',
    Exception: 'Exception',
    LogData: 'Data Log',
    Announcement: 'Announcement',
    SQL: 'SQL',
    StoreManagement: 'Store Management',
    POS: 'POS - Selling',
    Info: 'Information',
    Exit: 'Exit',
    POSDesc: 'Click here to make orders',
    Vietnamese: 'Vietnamese',
    English: 'English'
}