var gVNResource = {
    General: 'Tổng Quan',
    Orders: 'Đơn hàng',
    Order: 'Đơn hàng',
    Products: 'Hàng hóa',
    Customers: 'Khách hàng',
    Purchase: 'Nhập kho',
    Inventory: 'Tồn kho',
    Revenue: 'Doanh số',
    Payment: 'Thu chi',
    Profit: 'Lợi nhuận',
    Setting: 'Thiết lập',
    Exception: 'Exception',
    LogData: 'Data Log',
    Announcement: 'Thông báo',
    SQL: 'SQL',
    StoreManagement: 'Quản lý cửa hàng',
    POS: 'POS - Bán hàng',
    Info: 'Thông tin',
    Exit: 'Thoát',
    POSDesc: 'Nhấp vào đây để bán hàng',
    Vietnamese: 'Tiếng Việt',
    English: 'Tiếng Anh',
    TodayActivity: 'Hoạt động hôm nay',
    NumOrder: 'Số đơn hàng',
    NumProduct: 'Số hàng hóa',
    RemovedOrder: 'Đơn hàng bị xóa',
    Activity: 'Hoạt động',
    Day: 'Day',
    Week: 'Tuần',
    Month: 'Tháng',
    Quarter: 'Quí',
    LastQuarter: 'Quí trước',
    ThisWeek: 'Tuần này',
    LastWeek: 'Tuần trước',
    ThisMonth: 'Tháng này',
    LastMonth: 'Tháng trước',
    FromDate: 'Từ ngày',
    ToDate: 'Đến ngày',
    InventoryInfo: 'Thông tin kho',
    LongWaiting: 'Tồn kho lâu',
    OutOfStore: 'Hết hàng',
    UnderLimit: 'Dưới định mức',
    OverLimit: 'Vượt định mức',
    ProductInfo: 'Thông tin hàng hóa',
    NotYetPrice: 'Chưa làm giá bán',
    NotYetCost: 'Chưa nhập giá mua',
    NotYetGroup: 'Hàng chưa phân loại',
    ChartRevenueWeek: 'Biểu đồ doanh số tuần',
    Announcement: 'Thông báo',
    NoAnnouncement: 'Chưa có thông báo!',
    MakeOrder: 'Bán hàng',
    MakeOrder2: 'Tạo đơn hàng',
    ExportExcel: 'Xuất Excel',
    PlaceholderOrder: 'Nhập mã đơn hàng hoặc thông tin khách hàng (mã, tên, SĐT)',
    DebtOrders: 'Đơn hàng còn nợ',
    OrderCode: 'Mã đơn hàng',
    Store: 'Cửa hàng',
    SoldDate: 'Ngày bán',
    Cashier: 'Thu ngân',
    Status: 'Trạng thái',
    SumMoney: 'Tổng tiền',
    Debit: 'Nợ',
    SumOrder: 'Tổng hóa đơn',
    NoDataFound: 'Không có dữ liệu!',
    NumRow: 'Số dòng',
    Total: 'Tổng',
    PrintOrder: 'In đơn hàng',
    TempSave: 'Lưu tạm',
    Save: 'Lưu',
    SaveAndPrint: 'Lưu và in',
    Back: 'Trở về',
    ListProducts: 'Danh sách hàng hóa'
}
//<span ng-bind="Language.Resource.StoreManagement"></span>
var gENResource = {
    General: 'General',
    Orders: 'Orders',
    Order: 'Order',
    Products: 'Products',
    Customers: 'Customers',
    Purchase: 'Purchase',
    Inventory: 'Inventory',
    Revenue: 'Revenue',
    Payment: 'Payment',
    Profit: 'Profit',
    Setting: 'Setting',
    Exception: 'Exception',
    LogData: 'Data Log',
    Announcement: 'Announcement',
    SQL: 'SQL',
    StoreManagement: 'Store Management',
    POS: 'POS - Selling',
    Info: 'Information',
    Exit: 'Exit',
    POSDesc: 'Click here to make orders',
    Vietnamese: 'Vietnamese',
    English: 'English',
    TodayActivity: 'Today Activity',
    NumOrder: 'Num of Orders',
    NumProduct: 'Num of Products',
    RemovedOrder: 'Removed Orders',
    Activity: 'Activity',
    Day: 'Day',
    Week: 'Week',
    Month: 'Month',
    Quarter: 'Quarter',
    LastQuarter: 'Last Quarter',
    ThisWeek: 'This week',
    LastWeek: 'Last week',
    ThisMonth: 'This month',
    LastMonth: 'Last month',
    FromDate: 'From Date',
    ToDate: 'To Date',
    InventoryInfo: 'Inventory Info',
    LongWaiting: 'Long waiting',
    OutOfStore: 'Out of Store',
    UnderLimit: 'Under limit',
    OverLimit: 'Over limit',
    ProductInfo: 'Product Info',
    NotYetPrice: 'Not input price',
    NotYetCost: 'Not input cost',
    NotYetGroup: 'Not input group',
    ChartRevenueWeek: 'Chart revenue in week',
    Announcement: 'Announcement',
    NoAnnouncement: 'No announcement!',
    MakeOrder: 'Make Order',
    MakeOrder2: 'Make Order',
    ExportExcel: 'Export Excel',
    PlaceholderOrder: 'Enter order code or customer\'s information (code, name, phone)',
    DebtOrders: 'Orders With Debit',
    OrderCode: 'Order Code',
    Store: 'Store',
    SoldDate: 'Sold Date',
    Cashier: 'Cashier',
    Status: 'Status',
    SumMoney: 'Sum Money',
    Debit: 'Debit',
    SumOrder: 'Num of Orders',
    NoDataFound: 'No Data Found!',
    NumRow: 'Num rows',
    Total: 'Total',
    PrintOrder: 'Print Order',
    TempSave: 'Temp Save',
    Save: 'Save',
    SaveAndPrint: 'Save and Print',
    Back: 'Back',
    ListProducts: 'List Products'
}