//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_System_Configuration_Data_List
    {
        public string Id { get; set; }
        public string Description { get; set; }
        public string TableName { get; set; }
        public string Colums { get; set; }
        public string Condition { get; set; }
        public string OrderColums { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
